spring:
#  cloud:
#    function:
#      scan:
#        packages: com.example.solace.decode.function
#      definition: getMessageIdFromDestination|getMessage;saveMessage;provisionQueue|saveQueue
#    stream:
#      bindings:
#        saveMessage-in-0:
#          destination: message
#          group: store
#          consumer:
#            concurrency: 2
#        provisionQueue|saveQueue-in-0:
#          destination: provision/queue
#        getMessageIdFromDestination|getMessage-in-0:
#          destination: print/message/*
#      solace:
#        default:
#          consumer:
#            queueMaxMsgRedelivery: 3

  # Elasticsearch Config
  elasticsearch:
    rest:
      uris: localhost:9200
      username: elastic
      password: changeme

  # MongoDB Config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messaging_db
      username: admin
      password: admin
      authentication-database: admin #TODO Setup user credentials instead of using admin

  # MariaDB Config
  datasource:
    url: jdbc:mariadb://localhost:3306/messaging_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: userA
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB53Dialect

# Solace PubSub+ Config
solace:
  java:
    host: tcps://mr16jp1pl8afc3.messaging.solace.cloud:55443
    msgVpn: troubleflipper
    userName: solace-cloud-client
    clientUsername: server
    clientPassword: v5jio5c4chmfsf9mtflehlaj14
    connectRetries: 3
    reconnectRetries: -1

logging:
  level:
    # Workaround for https://github.com/spring-projects/spring-data-elasticsearch/issues/1675
    # Return log-level for this class to INFO once spring-data-elasticsearch 4.2.X is released
    org.springframework.data.convert.CustomConversions: ERROR

server:
  port: 8085
